#spring:
#  config:
#    import: "optional:configserver:http://config-server:8088"
#    activate:
#      on-profile: docker

spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://config-server:8888
  profiles:
    active: docker
management:
  security:
    enabled: false
---
spring:
  application:
    name: discovery-service
  config:
    import: "optional:configserver:http://localhost:8088"