spring:
  config:
    import: "optional:configserver:http://config-server-1:8088"
    activate:
      on-profile: docker

---
spring:
  application:
    name: discovery-service
  config:
    import: "optional:configserver:http://localhost:8088"